Import('*')

env = env.Copy(tools=['Renaissance', 'Boost', 'BoostTest'])

sources = Split("""
    TestMain.cpp

    BasicProgram.cpp
    Comments.cpp
    ConstantProgram.cpp
    EmptyProgram.cpp
    ErrorLine.cpp
    Expression.cpp
    Functions.cpp
""")

runner = env.Program('testRunner', sources)
test_alias = Alias('test', [runner], runner[0].path)
AlwaysBuild(test_alias)
