Import('*')

env = env.Copy(tools=['Renaissance', 'Boost', 'BoostTest'])

sources = Split("""
    TestMain.cpp

    Attributes.cpp
    BasicProgram.cpp
    Branch.cpp
    CodeGeneration.cpp
    Comments.cpp
    ConstantProgram.cpp
    EmptyProgram.cpp
    ErrorLine.cpp
    Errors.cpp
    Expression.cpp
    Functions.cpp
    Literals.cpp
    Sharing.cpp
    Swizzle.cpp
    Uniforms.cpp
    VectorConcatenation.cpp

    Types.cpp
""")

# Depend on the test programs so that typing "scons test" makes everything
# for test.py up-to-date as well.
testProgramsLocation = Dir('#/stage/bin')

runner = env.Program('testRunner', sources)
AlwaysBuild( env.Alias('test', [runner, testProgramsLocation], runner[0].path) )
