Import('*')

env = env.Copy(tools=['SDL', 'OpenGL', 'Renaissance', 'Boost'])

sources = Split("""
    glew.c
""")

env.Program('temperature', ['temperature.cpp'] + sources)
env.Program('brick',       ['brick.cpp']       + sources)
