Import('*')

env = env.Copy(tools=['Boost'])

env.Command(['ShaderLexer.cpp', 'ShaderLexer.hpp',
             'ShaderLexerTokenTypes.hpp', 'ShaderLexerTokenTypes.txt',
             'ShaderParser.cpp', 'ShaderParser.hpp',
             'ShaderValidator.cpp', 'ShaderValidator.hpp'],
            'Shader.g',
            'antlr -o $TARGET.dir $SOURCES')

# Shared library.
env.Library('common', Split("""
    Compiler.cpp
    Definition.cpp
    Program.cpp

    ShaderLexer.cpp
    ShaderParser.cpp
    ShaderValidator.cpp
"""))
env.Append(CPPPATH=['.'], LIBPATH=['.'], LIBS=['common'])
env.Append(LIBS=['antlr'])

env.Install('#', [
    env.Program('testLexer.cpp'),
    env.Program('testParser.cpp'),
    env.Program('testValidator.cpp'),
    env.Program('testCompiler.cpp')])
