Import('*')

env.Command(['ShaderLexer.cpp', 'ShaderLexer.hpp',
             'ShaderLexerTokenTypes.hpp', 'ShaderLexerTokenTypes.txt',
             'ShaderParser.cpp', 'ShaderParser.hpp'],
            'Shader.g',
            'antlr -o $TARGET.dir $SOURCES')
env.Append(LIBS=['antlr'])

testLexer = env.Program('testLexer', Split("""
    testLexer.cpp
    ShaderLexer.cpp
"""))

testParser = env.Program('testParser', Split("""
    testParser.cpp
    ShaderLexer.cpp
    ShaderParser.cpp
"""))

env.Install('#', [testLexer, testParser])
